apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testwebapp.fullname" . }}
  labels:
    {{- include "testwebapp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "testwebapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "testwebapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "testwebapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:          
            - name: "MYSQL_DB_HOST"
              valueFrom:
                secretKeyRef:
                  key:  MYSQL_DB_HOST
                  name: {{ .Release.Name }}-db-creds
            - name: "MYSQL_DB_USER"
              valueFrom:
                secretKeyRef:
                  key:  MYSQL_DB_USER
                  name: {{ .Release.Name }}-db-creds
            - name: "MYSQL_DB_USER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key:  MYSQL_DB_USER_PASSWORD
                  name: {{ .Release.Name }}-db-creds
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /demo/all
              port: http
          readinessProbe:
            httpGet:
              path: /demo/all
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
