apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-creds
data:
  MYSQL_DB_USER: {{ .Values.secret.dbUser | b64enc }}
  MYSQL_DB_USER_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}
  MYSQL_DB_HOST: {{ .Values.secret.dbHost | b64enc }}